apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: flask-app:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
        envFrom:
          - secretRef:
              name: llmops-secrets    
        resources:
          requests:
            cpu: 500m       # Request: half a CPU core
            memory: 512Mi   # Request: 512MB RAM
          limits:
            cpu: 1          # Limit: 1 CPU core
            memory: 1Gi     # Limit: 1GB RAM

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000              